### ISSUE TITLE
Not installable in Emacs 29

### ISSUE THREAD

**Issue by haplo** [intramurz/flycheck-eglot#2]
I'm running Emacs 29.1 and I don't see the package as available to install. `package-install` shows every other package in MELPA but not `flycheck-eglot`.

`package-archives` is:

```elisp
(("gnu" . "https://elpa.gnu.org/packages/")
 ("nongnu" . "https://elpa.nongnu.org/nongnu/")
 ("melpa-stable" . "https://stable.melpa.org/packages/"))
```

Is this because of the requirement definition? Should it be expanded to `>=28.1`?

https://github.com/intramurz/flycheck-eglot/blob/9ff8d0068be59b1450964b390349d75a68af21ed/flycheck-eglot.el#L8

Thank you for *flycheck-eglot* and your support!

**Comment by intramurz** [comment]
This package is not in the stable `MELPA`. Maybe this is the point? Try adding `("melpa" . "https://melpa.org/packages/")` to `package-archives`, maybe it will help. Keep in mind that by default `melpa` will take precedence over `melpa-stable`.

Thank you for your interest in `flycheck-eglot`. Good luck.

**Comment by haplo** [comment]
> This package is not in the stable `MELPA`. Maybe this is the point? Try adding `("melpa" . "https://melpa.org/packages/")` to `package-archives`, maybe it will help. Keep in mind that by default `melpa` will take precedence over `melpa-stable`.
> 
> Thank you for your interest in `flycheck-eglot`. Good luck.

Ah, I just assumed that it would be on MELPA stable, sorry for not checking regular MELPA.

I set it up so only *flycheck-eglot* would be installed from MELPA, while other packages will favor MELPA stable by setting `(setq use-package-always-pin "melpa-stable")` (see this [SO answer](https://emacs.stackexchange.com/a/33763)), and it worked like a charm. For anyone interested here is [the commit in my configuration](https://github.com/haplo/dotemacs/commit/f62484a4a12dfbc6dff51f195b28d9e4380725e2).

Thank you again!
