### ISSUE TITLE
Moving under the Flycheck org

### ISSUE THREAD

**Issue by bbatsov** [intramurz/flycheck-eglot#3]
Hey there!

I'm the new maintainer for Flycheck and I noticed your package today. Cool stuff! Especially since I was pondering today what to do about an integration with Eglot... 😄 

Let me know if you'd be interested in moving it under the official Flycheck GitHub org, which I hope will increase it's visibility.

**Comment by intramurz** [comment]
Hi!

Thank you for your appreciation of my work. As for moving the project, it’s an excellent, although a little unexpected, proposal - I accept it, why not. I suppose it will be necessary to correct the details in MELPA. I would be happy to continue maintaining the package (if necessary).

P.S. It seems to me that the visibility of packages is most affected by references in official documentation and other sources. :slightly_smiling_face:

**Comment by bbatsov** [comment]
Thanks for the quick response!

`flycheck-eglot` is already mentioned here https://www.flycheck.org/en/latest/user/flycheck-versus-flymake.html#supported-by-eglot 
At some point I'll feature it more prominently in the docs - once I get to writing some dedicated section about Eglot and lsp-mode. 

> Thank you for your appreciation of my work. As for moving the project, it’s an excellent, although a little unexpected, proposal - I accept it, why not. I suppose it will be necessary to correct the details in MELPA. I would be happy to continue maintaining the package (if necessary).

You'll continue to be a maintainer for the project after you join the Flycheck org. I'll send you an invitation to join the org and after you've accepted it you can do the transfer.

**Comment by intramurz** [comment]
Thank you! I'm moving...
